variable "env" {}
variable "project-name" {}
variable "vpc_cidr_block" {}
variable "azs" {}
variable "public_subnet_cidrs" {}
variable "private_subnet_cidrs" {}
variable "database_subnet_cidrs" {}
variable "account_no" {}
variable "default_vpc_id" {}
